#!/bin/sh
set -eu

DIR=$(dirname "$0")
AUTH=$(cat "$DIR/.test-curl-auth")
SERVER=${SERVER:-"http://localhost:12022"}

FILE=$1

exec curl --verbose --fail-with-body --insecure -u "$AUTH" "$SERVER/data/$FILE"
