#!/usr/bin/env bash
# (for arrays)
set -eu

DIR=$(dirname "$0")
AUTH=$(cat "$DIR/.test-curl-auth")
SERVER=${SERVER:-"http://localhost:12022"}

if [ $# = 0 ] ; then
    echo "missing file arguments" >&2
    exit 1
fi

FILEARGS=()
for file ; do
    FILEARGS+=( -F file=@"$file" )
done

exec curl --verbose --fail-with-body --insecure -u "$AUTH" "$SERVER/data" "${FILEARGS[@]}"
